apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: httpd-example-route
  namespace: "{{ .Values.environmentName }}-test"
spec:
  host: "iwork-{{ -Values.environmentName }}-test.apps.ocp4.bofh.ninja"
  to:
    kind: Service
    name: httpd-example

